version: "3"
services:
  mongo:
    container_name: p4nth3rb0t-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: p4nth3rb0t
      MONGO_INITDB_ROOT_PASSWORD: supersecretpassword

  mongo-express:
    container_name: p4nth3rb0t-mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: p4nth3rb0t
      ME_CONFIG_MONGODB_ADMINPASSWORD: supersecretpassword
